name: CI

on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'images/**'
  push:
    paths-ignore:
      - 'docs/**'
      - 'images/**'

jobs:
  lint:
    name: "Linting"
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: '17.x'
      - name: Install Yarn
        run: npm install -g yarn
      - name: Restore cache
        uses: actions/cache@v1
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-ci-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-ci-${{ env.cache-name }}-
      - name: Install packages
        run: yarn
      - name: Building
        run: yarn build
      - name: Bundling
        run: yarn bundle
      - name: Generating docs
        run: yarn docs
