name: CI

on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'images/**'
  push:
    paths-ignore:
      - 'docs/**'
      - 'images/**'

jobs:
  lint:
    name: "Building"
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install pnpm
        run: npm install -g pnpm@latest-10
      - name: Restore cache
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: |
            ~/.pnpm-store
            node_modules
          key: ${{ runner.os }}-ci-${{ env.cache-name }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-ci-${{ env.cache-name }}-
      - name: Install packages
        run: pnpm install
      - name: Building
        run: pnpm build
      - name: Running tests
        run: pnpm test
      - name: Generating docs
        run: pnpm run docs
